automation: use 3.6 repos
Fixes:
DEBUG util.py:421:  Error: Package:
vdsm-4.18.999-232.git6e84643.el7.centos.x86_64 (ovirt)
DEBUG util.py:421:             Requires: openvswitch >= 2.0.0

within:
http://jenkins.ovirt.org/job/ovirt-node-plugin-hosted-engine_ovirt-3.6_check-merged-el7-x86_64/

Change-Id: I40ca43c4efc23fd344085168bce8943e26f58c4e
Signed-off-by: Sandro Bonazzola <sbonazzo@redhat.com>
Reviewed-on: https://gerrit.ovirt.org/61967
Continuous-Integration: Jenkins CI
Reviewed-by: Douglas Schilling Landgraf <dougsland@redhat.com>